name: Deploy HTML App to Azure

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_DIR: terraform
      WEBAPP_DIR: webapp
      ZIP_NAME: site.zip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check if already deployed
        id: check
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            exists=$(az group exists --name lesson6-rg)
            echo "exists=$exists" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        if: steps.check.outputs.exists == 'false'
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        if: steps.check.outputs.exists == 'false'
        run: terraform -chdir=${{ env.TF_DIR }} init

      - name: Terraform Apply
        if: steps.check.outputs.exists == 'false'
        run: terraform -chdir=${{ env.TF_DIR }} apply -auto-approve

      - name: Capture Webapp Name
        id: tfout
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            webapp_name=$(az webapp list --resource-group lesson6-rg --query "[0].name" --output tsv)
            echo "webapp_name=$webapp_name" >> $GITHUB_OUTPUT

      - name: Package Static Site
        run: |
          cd ${{ env.WEBAPP_DIR }}
          zip -r ../${{ env.ZIP_NAME }} .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ steps.tfout.outputs.webapp_name }}
          package: ./${{ env.ZIP_NAME }}
